# Generated by Django 4.2 on 2023-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
